### ISSUE TITLE
Discored Update 0.0.298 

### ISSUE THREAD

**Issue by vincentdjojo** [Azagwen/Rainbow_kittens_theme#1]
Not working after this update. Please fix this. Thanks

**Comment by vincentdjojo** [comment]
Discord added their own title bar and it the menu is not longer transparent so I can't see the kittens in the background except when you open settings.

**Comment by Azagwen** [comment]
Fixed this
Please say hello or at least introduce what you'll say
I'm human, thanks

**Comment by vincentdjojo** [comment]
Sorry. That was my first post.

**Comment by vincentdjojo** [comment]
Hi Azagwen. There's still a transparency problem with a bar on the top of discord.
![image](https://user-images.githubusercontent.com/33171330/32259835-6782c68a-befe-11e7-9892-bee4587dfc34.png)

**Comment by Azagwen** [comment]
what ?
I thought I fixed this one / _\

**Comment by Azagwen** [comment]
```
.theme-dark .headerBar-cxbhPD {
    background: var(--Background-overlay);
    box-shadow: 0 1px 0 rgba(0,0,0,.2), 0 2px 0 rgba(0,0,0,.06);
}
```

Add this to your custom CSS, I can't do an update just for this, but it will do the job waiting for the next update.
And thanks for the watch > uo

**Comment by vincentdjojo** [comment]
Thanks man! Love this theme a lot.

**Comment by Azagwen** [comment]
ugh I'm not a man but it doesn't sound good with "thanks girl" . _.

**Comment by vincentdjojo** [comment]
Thanks grill
