### ISSUE TITLE
Missing META

### ISSUE THREAD

**Issue by Sk3tch12E** [Azagwen/Rainbow_kittens_theme#11]
theme.css file is missing its META data at the start
It  should look something like this:
/**
 * @name RainbowKittensTheme
 * @version Auto
 * @description Just a simple theme to have rainbow kittens
 * 
 * @website probably the github link or your twitter
 */

**Comment by Azagwen** [comment]
I stopped updating this theme years ago, so it must be missing a lot of things BD asks for nowadays.

Feel free to update it yourself if you really want it working again, I won't be able to do that anymore on my end for various reasons.

**Comment by Sk3tch12E** [comment]
I have updated it and created a pull request so that when people get the theme from the discord they can get it in a working state.
