### ISSUE TITLE
Background not working once again.

### ISSUE THREAD

**Issue by vincentdjojo** [Azagwen/Rainbow_kittens_theme#2]
![image](https://user-images.githubusercontent.com/33171330/35028154-79538426-fb8f-11e7-8b65-8724ec62e578.png)
Hello Azagwen!
Once again Discord is screwing with their css.
Seems like the background is not working but the title bar is working.
Would you care to have a look?
Thanks lady.

**Comment by Azagwen** [comment]
I'll see! Thanks for noticing me 
it's a bit hard for me to notice issues because my discord is rarely closed ^^'

**Comment by vincentdjojo** [comment]
Hey Azagwen.
Is everything alright?
Did you fix the issue?

**Comment by Azagwen** [comment]
yes It's fixed now
there is still a slight risk of themes not working on some computers, but that's because of BD itself ^^
(I'll close the issue When you'll tell if it works or not)
