### ISSUE TITLE
Two Themes

### ISSUE THREAD

**Issue by yessitsjess** [Azagwen/Rainbow_kittens_theme#3]
The theme only works when I apply another theme with it. 
![twothemes](https://user-images.githubusercontent.com/35271050/36285900-3ea718d0-1262-11e8-8dc6-8223baf4c1e8.PNG)

**Comment by Azagwen** [comment]
Sorry for the replying time, I usually never go on github other then when I update the theme.
I don't know why this issue happens but I can say I updated it, try it as soon as you can before discord updates again, I'm pretty sure new issues will came with another update as well.
