### ISSUE TITLE
Game section

### ISSUE THREAD

**Issue by vincentdjojo** [Azagwen/Rainbow_kittens_theme#5]
Yo Azagwen,
Dankboi69 reporting in.
Discord has this new game section.
Are you willing to take the challenge? 

![image](https://user-images.githubusercontent.com/33171330/43058214-0be4367e-8e79-11e8-9496-644412130b2e.png)

**Comment by vincentdjojo** [comment]
![image](https://user-images.githubusercontent.com/33171330/43058189-e05e5f84-8e78-11e8-8203-0e0e2f520b2e.png)
Btw, the window buttons are abit off when Discord is windowed. 
Could you fix that too?
Thanks

**Comment by Azagwen** [comment]
Game section has been updated in 1.1.2
feel free to check

also for windows buttons a I'm still investigating
