### ISSUE TITLE
New sections library and store, settings section stopped working

### ISSUE THREAD

**Issue by vincentdjojo** [Azagwen/Rainbow_kittens_theme#6]
Hello Azagwen!
Once again, Discord has updated.
There's a new section called Library and Store. The theme reverts to the black theme when on these sections. The settings section seems to revert to the black theme too.
Could you please fix it?
Thank you!

Vincent

**Comment by Azagwen** [comment]
Hi !
Sorry for the inconvenience, I'll try to address that issue as soon as I have time !

**Comment by Azagwen** [comment]
an Update will be released today, very soon !
