### ISSUE TITLE
Discord Light Theme Update broke themes

### ISSUE THREAD

**Issue by juli4nne** [Azagwen/Rainbow_kittens_theme#8]
The recent update has broken almost all themes. Since I can't edit the files for personal use, please update it to work.

**Comment by Azagwen** [comment]
Thanks for telling me ! My discord wasn't up to date for some reasons.

Gotta fix it asap.

**Comment by Azagwen** [comment]
I've updated it, it should reload by itself, if it doesn't do it instantly it's gonna do it later once it notices the file has been changed. 

I keep this open for now in case it doesn't reload. Tell me if this happens.
