### ISSUE TITLE
can i get this as a gif or something

### ISSUE THREAD

**Issue by ghost** [Azagwen/Rainbow_kittens_theme#9]
i want this as a gif/video so i can make it my wallpaper idk how to do it from code or if its possible tho

**Comment by Azagwen** [comment]
could you be more precise ?

**Comment by ghost** [comment]
i was able to find the picture of the cats but it was just in burple i would like it to change colours like it does in discord idk if that would be to hard tho

**Comment by Azagwen** [comment]
what does this have to do with my theme ?

**Comment by Azagwen** [comment]
I'll close this issue, please DM me on discord when you have questions that are not related to the theme itself.
